import logging
import pandas as pd

import pymysql

import pymysql
def get_team_info(team):
    team_info = {
        'Rio Ave FC': {'league': 'Primeira Liga', 'rank': 1, 'country': 'Portugal'},
        'SL Benfica': {'league': 'Primeira Liga', 'rank': 1, 'country': 'Portugal'},
        'Manchester City': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Arminia Bielefeld U19': {'league': 'Unknown', 'rank': None, 'country': 'Unknown'},
        'Arminia Bielefeld': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'TSV 1860 Munich': {'league': '3. Liga', 'rank': 3, 'country': 'Germany'},
        'Leeds United': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Liverpool FC': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Charlton Athletic': {'league': 'EFL League One', 'rank': 3, 'country': 'England'},
        'Aston Villa': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Bursaspor': {'league': 'TFF First League', 'rank': 2, 'country': 'Turkey'},
        'Wigan Athletic': {'league': 'EFL League One', 'rank': 3, 'country': 'England'},
        'Derby County': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'SL Benfica B': {'league': 'LigaPro', 'rank': 2, 'country': 'Portugal'},
        'Chelsea FC': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Watford FC': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'AFC Bournemouth': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Barnsley FC U18': {'league': 'Unknown', 'rank': None, 'country': 'Unknown'},
        'Barnsley FC': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Everton FC': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Athletic Bilbao': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'FC Winterthur': {'league': 'Challenge League', 'rank': 2, 'country': 'Switzerland'},
        'FC Basel 1893': {'league': 'Super League', 'rank': 1, 'country': 'Switzerland'},
        'Borussia Dortmund': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'SD Huesca': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'RSC Anderlecht': {'league': 'Jupiler Pro League', 'rank': 1, 'country': 'Belgium'},
        'Sheffield United': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Tottenham Hotspur': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Villarreal CF': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Atlético de Madrid': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'CA Vélez Sarsfield': {'league': 'Liga Profesional Argentina', 'rank': 1, 'country': 'Argentina'},
        'VfL Bochum U19': {'league': 'Unknown', 'rank': None, 'country': 'Unknown'},
        '1.FC Nuremberg': {'league': '2. Bundesliga', 'rank': 2, 'country': 'Germany'},
        'KRC Genk': {'league': 'Jupiler Pro League', 'rank': 1, 'country': 'Belgium'},
        'SV Werder Bremen': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'VfL Wolfsburg': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'AS Monaco': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'Manchester City U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Notts County': {'league': 'National League', 'rank': 5, 'country': 'England'},
        'AC Le Havre': {'league': 'Ligue 2', 'rank': 2, 'country': 'France'},
        'Leicester City': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Bryne FK': {'league': 'PostNord-ligaen Avd 1', 'rank': 4, 'country': 'Norway'},
        'Molde FK': {'league': 'Eliteserien', 'rank': 1, 'country': 'Norway'},
        'Red Bull Salzburg': {'league': 'Austrian Bundesliga', 'rank': 1, 'country': 'Austria'},
        'CA River Plate II': {'league': 'Primera B Nacional', 'rank': 2, 'country': 'Argentina'},
        'CA River Plate': {'league': 'Liga Profesional Argentina', 'rank': 1, 'country': 'Argentina'},
        'Stade Reims': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'Stade Rennais FC': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'CD Basconia': {'league': 'Tercera División - Group 4', 'rank': 4, 'country': 'Spain'},
        'SD Ponferradina': {'league': 'La Liga 2', 'rank': 2, 'country': 'Spain'},
        'Real Valladolid CF': {'league': 'La Liga 2', 'rank': 2, 'country': 'Spain'},
        'Chicago Fire FC': {'league': 'Major League Soccer', 'rank': 1, 'country': 'United States'},
        'Fulham FC': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Middlesbrough FC': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'AS Saint-Étienne': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'FC Metz': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'SSC Napoli': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Ipswich Town': {'league': 'EFL League One', 'rank': 3, 'country': 'England'},
        'Chelsea FC U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Huddersfield Town': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'FC Lorient': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'FC Porto': {'league': 'Primeira Liga', 'rank': 1, 'country': 'Portugal'},
        'Fluminense Football Club': {'league': 'Brasileirão Série A', 'rank': 1, 'country': 'Brazil'},
        'AC Milan': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Paris Saint-Germain': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'FC Barcelona U19': {'league': 'Unknown', 'rank': None, 'country': 'Spain'},
        'FC Barcelona B': {'league': 'Segunda División B', 'rank': 4, 'country': 'Spain'},
        'SD Eibar': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Getafe CF': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Brighton & Hove Albion': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Chelsea FC U21': {'league': 'Papa Johns Trophy', 'rank': None, 'country': 'England'},
        'CA Osasuna': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Olympique Marseille': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'Defensa y Justicia': {'league': 'Liga Profesional Argentina', 'rank': 1, 'country': 'Argentina'},
        'US Boulogne': {'league': 'Championnat National', 'rank': 3, 'country': 'France'},
        'SM Caen': {'league': 'Championnat National', 'rank': 3, 'country': 'France'},
        'Servette FC': {'league': 'Super League', 'rank': 1, 'country': 'Switzerland'},
        'BSC Young Boys': {'league': 'Super League', 'rank': 1, 'country': 'Switzerland'},
        'Borussia Mönchengladbach': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'Juventus FC': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'GNK Dinamo Zagreb': {'league': '1. HNL', 'rank': 1, 'country': 'Croatia'},
        'FC Internazionale': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Inter Milan': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Real Madrid': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Swansea City': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Crystal Palace': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Chelsea FC U18': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Aston Villa U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Vitesse Arnhem': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'Bayer 04 Leverkusen': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'Arsenal Kyiv': {'league': 'Unknown', 'rank': None, 'country': 'Ukraine'},
        'Desna Chernigiv': {'league': 'Ukrainian Premier League', 'rank': 1, 'country': 'Ukraine'},
        'Shakhtar Donetsk': {'league': 'Ukrainian Premier League', 'rank': 1, 'country': 'Ukraine'},
        'PSV Eindhoven U21': {'league': 'Unknown', 'rank': None, 'country': 'Netherlands'},
        'PSV Eindhoven': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'SC Heerenveen': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'Twente Enschede FC': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'Ajax Amsterdam': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'SL Benfica U19': {'league': 'Unknown', 'rank': None, 'country': 'Portugal'},
        'Southampton FC': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Dijon FCO': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'LOSC Lille': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'Arsenal FC': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'FC Barcelona': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Sport Club Internacional B': {'league': 'Campeonato Brasileiro Série B', 'rank': 1, 'country': 'Brazil'},
        'Sport Club Internacional': {'league': 'Campeonato Brasileiro Série A', 'rank': 1, 'country': 'Brazil'},
        'AS Roma': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Real Betis Balompié': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'West Ham United': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'FC Groningen U21': {'league': 'Unknown', 'rank': None, 'country': 'Netherlands'},
        'FC Groningen': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'Celtic FC': {'league': 'Scottish Premiership', 'rank': 1, 'country': 'Scotland'},
        'FC Sochaux-Montbéliard': {'league': 'Ligue 2', 'rank': 2, 'country': 'France'},
        'RB Leipzig': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'FC Schalke 04': {'league': '2. Bundesliga', 'rank': 18, 'country': 'Germany'},
        'VfB Stuttgart': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'Blackpool FC': {'league': 'EFL Championship', 'rank': 3, 'country': 'England'},
        'Dundee United FC': {'league': 'Scottish Premiership', 'rank': 5, 'country': 'Scotland'},
        'Hull City': {'league': 'EFL League One', 'rank': 1, 'country': 'England'},
        'Olympiakos Piräus U20': {'league': 'Unknown', 'rank': None, 'country': 'Greece'},
        'Olympiacos Piraeus': {'league': 'Super League Greece', 'rank': 1, 'country': 'Greece'},
        'Esbjerg fB': {'league': 'NordicBet Liga', 'rank': 1, 'country': 'Denmark'},
        'Willem II Tilburg': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'Aberdeen FC B': {'league': 'Unknown', 'rank': None, 'country': 'Scotland'},
        'Aberdeen FC': {'league': 'Scottish Premiership', 'rank': 4, 'country': 'Scotland'},
        'Real Madrid Castilla': {'league': 'Segunda División B', 'rank': 4, 'country': 'Spain'},
        'Bayern Munich': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'Liverpool FC U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Grêmio Foot-Ball Porto Alegrense B (-2022)': {'league': 'Unknown', 'rank': None, 'country': 'Brazil'},
        'Grêmio Foot-Ball Porto Alegrense': {'league': 'Campeonato Brasileiro Série A', 'rank': 1, 'country': 'Brazil'},
        'Sunderland AFC': {'league': 'EFL League One', 'rank': 2, 'country': 'England'},
        'Southampton FC U18': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Newcastle United': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Blackburn Rovers': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Fulham FC U21': {'league': 'Papa Johns Trophy', 'rank': None, 'country': 'England'},
        'Barranquilla FC': {'league': 'Categoría Primera B', 'rank': 2, 'country': 'Colombia'},
        'Junior FC': {'league': 'Liga BetPlay DIMAYOR', 'rank': 1, 'country': 'Colombia'},
        'PSV Eindhoven U19': {'league': 'Unknown', 'rank': None, 'country': 'Netherlands'},
        'FC Paços de Ferreira U19': {'league': 'Unknown', 'rank': None, 'country': 'Portugal'},
        'FC Paços de Ferreira': {'league': 'Primeira Liga', 'rank': 4, 'country': 'Portugal'},
        'Wolverhampton Wanderers': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'El Mokawloon SC': {'league': 'Egyptian Premier League', 'rank': 1, 'country': 'Egypt'},
        'ACF Fiorentina': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'CA Peñarol': {'league': 'Primera División', 'rank': 1, 'country': 'Uruguay'},
        'UD Almería': {'league': 'La Liga SmartBank', 'rank': 1, 'country': 'Spain'},
        'TSG 1899 Hoffenheim': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'Richmond Kickers': {'league': 'USL League One', 'rank': 6, 'country': 'United States'},
        'New England Revolution': {'league': 'Major League Soccer', 'rank': 1, 'country': 'United States'},
        'OGC Nice': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'Avaí Futebol Clube (SC)': {'league': 'Campeonato Brasileiro Série B', 'rank': 2, 'country': 'Brazil'},
        'ESTAC Troyes': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'FK Zeleziarne Podbrezova': {'league': 'Fortuna Liga', 'rank': 9, 'country': 'Slovakia'},
        'MSK Zilina': {'league': 'Fortuna Liga', 'rank': 7, 'country': 'Slovakia'},
        'Spezia Calcio': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Bolton Wanderers': {'league': 'EFL League Two', 'rank': 2, 'country': 'England'},
        'FK Ufa': {'league': 'Russian Premier League', 'rank': 9, 'country': 'Russia'},
        'Celtic Glasgow U20': {'league': 'Unknown', 'rank': None, 'country': 'Scotland'},
        'Avispa Fukuoka': {'league': 'J1 League', 'rank': 1, 'country': 'Japan'},
        'Sint-Truidense VV': {'league': 'Jupiler Pro League', 'rank': 1, 'country': 'Belgium'},
        'Bologna FC 1909': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'RCD Mallorca': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Hellas Verona': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Besiktas JK': {'league': 'Süper Lig', 'rank': 1, 'country': 'Turkey'},
        'Strømsgodset IF II': {'league': 'Unknown', 'rank': None, 'country': 'Norway'},
        'Strømsgodset IF': {'league': 'Eliteserien', 'rank': 1, 'country': 'Norway'},
        'Real Sociedad': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Arsenal FC U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'FC Porto B': {'league': 'Liga Portugal 2', 'rank': 1, 'country': 'Portugal'},
        'KRC Genk U19': {'league': 'Unknown', 'rank': None, 'country': 'Belgium'},
        'Lommel United': {'league': 'Eerste Klasse B', 'rank': 5, 'country': 'Belgium'},
        'Oud-Heverlee Leuven': {'league': 'Jupiler Pro League', 'rank': 1, 'country': 'Belgium'},
        'Feyenoord Rotterdam': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'Sociedade Esportiva Palmeiras': {'league': 'Campeonato Brasileiro Série A', 'rank': 2, 'country': 'Brazil'},
        'Atlético Madrid U19': {'league': 'Unknown', 'rank': None, 'country': 'Spain'},
        'Manchester United': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'Birmingham City': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Cheltenham Town': {'league': 'EFL League Two', 'rank': 1, 'country': 'England'},
        'Stoke City': {'league': 'EFL Championship', 'rank': 3, 'country': 'England'},
        'Royal Antwerp FC': {'league': 'Jupiler Pro League', 'rank': 1, 'country': 'Belgium'},
        'Cardiff City': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Bristol City': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Burnley FC': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'RC Lens': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'Västerås SK': {'league': 'Division 1 Norra', 'rank': 7, 'country': 'Sweden'},
        'Blackburn Rovers Reserves': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Norwich City': {'league': 'Premier League', 'rank': 1, 'country': 'England'},
        'FC Porto U19': {'league': 'Unknown', 'rank': None, 'country': 'Portugal'},
        'São Paulo Futebol Clube': {'league': 'Campeonato Brasileiro Série A', 'rank': 1, 'country': 'Brazil'},
        'Brentford FC': {'league': 'Premier League', 'rank': 9, 'country': 'England'},
        'FC Admira Wacker Mödling': {'league': 'Austrian Football Bundesliga', 'rank': 10, 'country': 'Austria'},
        'Rapid Vienna': {'league': 'Austrian Football Bundesliga', 'rank': 1, 'country': 'Austria'},
        'Ajax Amsterdam U21': {'league': 'Unknown', 'rank': None, 'country': 'Netherlands'},
        'Manchester United U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Manchester United U21': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Novara Calcio 1908': {'league': 'Serie C', 'rank': 3, 'country': 'Italy'},
        'Udinese Calcio': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'UC Sampdoria': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Sporting CP': {'league': 'Primeira Liga', 'rank': 2, 'country': 'Portugal'},
        'Deportivo Alavés': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'Sevilla FC': {'league': 'La Liga', 'rank': 1, 'country': 'Spain'},
        'FC Emmen': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'Heracles Almelo': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'AZ Alkmaar': {'league': 'Eredivisie', 'rank': 2, 'country': 'Netherlands'},
        'OGC Nice B': {'league': 'Unknown', 'rank': None, 'country': 'France'},
        'Olympique Lyon': {'league': 'Ligue 1', 'rank': 1, 'country': 'France'},
        'Degerfors IF': {'league': 'Allsvenskan', 'rank': 1, 'country': 'Sweden'},
        'Viborg FF': {'league': '1st Division', 'rank': 1, 'country': 'Denmark'},
        'Orlando City SC': {'league': 'Major League Soccer', 'rank': 1, 'country': 'United States'},
        'Belgrano de Córdoba II': {'league': 'Unknown', 'rank': None, 'country': 'Argentina'},
        'Club Atlético Belgrano': {'league': 'Primera Nacional', 'rank': 3, 'country': 'Argentina'},
        'Genoa CFC': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Atalanta BC': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Atlético Nacional': {'league': 'Liga BetPlay DIMAYOR', 'rank': 1, 'country': 'Colombia'},
        'AS Nancy-Lorraine B': {'league': 'Unknown', 'rank': None, 'country': 'France'},
        'AS Nancy-Lorraine': {'league': 'Ligue 2', 'rank': 6, 'country': 'France'},
        'Tottenham Hotspur U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'CF Peralada': {'league': 'Unknown', 'rank': None, 'country': 'Spain'},
        'Girona FC': {'league': 'Segunda División', 'rank': 3, 'country': 'Spain'},
        'AA Ponte Preta U17': {'league': 'Unknown', 'rank': None, 'country': 'Brazil'},
        'Clube Atlético Mineiro': {'league': 'Campeonato Brasileiro Série A', 'rank': 3, 'country': 'Brazil'},
        'FC Bayern Munich II': {'league': '3. Liga', 'rank': 6, 'country': 'Germany'},
        'FC Augsburg': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'CA Boca Juniors': {'league': 'Liga Profesional Argentina', 'rank': 1, 'country': 'Argentina'},
        'FC Sochaux-Montbéliard B': {'league': 'Unknown', 'rank': None, 'country': 'France'},
        'KSV Roeselare (- 2020)': {'league': 'Unknown', 'rank': None, 'country': 'Belgium'},
        'Club Brugge KV': {'league': 'Jupiler Pro League', 'rank': 1, 'country': 'Belgium'},
        'Hamburger SV': {'league': '2. Bundesliga', 'rank': 1, 'country': 'Germany'},
        'NEC Nijmegen': {'league': 'Eerste Divisie', 'rank': 1, 'country': 'Netherlands'},
        'Parma Calcio 1913': {'league': 'Serie B', 'rank': 1, 'country': 'Italy'},
        'América Futebol Clube (MG)': {'league': 'Campeonato Brasileiro Série A', 'rank': 16, 'country': 'Brazil'},
        'FC Slovan Liberec': {'league': 'Fortuna Liga', 'rank': 8, 'country': 'Czech Republic'},
        'AC Sparta Prague': {'league': 'Fortuna Liga', 'rank': 3, 'country': 'Czech Republic'},
        '1.FSV Mainz 05': {'league': 'Bundesliga', 'rank': 9, 'country': 'Germany'},
        '1.FC Union Berlin': {'league': 'Bundesliga', 'rank': 2, 'country': 'Germany'},
        'Carlisle United': {'league': 'EFL League Two', 'rank': 1, 'country': 'England'},
        'Motherwell FC': {'league': 'Scottish Premiership', 'rank': 3, 'country': 'Scotland'},
        'Darlington FC (- 2012)': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'FC Wil 1900': {'league': 'Challenge League', 'rank': 7, 'country': 'Switzerland'},
        'Deportivo de La Coruña': {'league': 'Segunda División B', 'rank': 1, 'country': 'Spain'},
        'Nottingham Forest': {'league': 'EFL Championship', 'rank': 1, 'country': 'England'},
        'St. Mirren FC': {'league': 'Scottish Premiership', 'rank': 6, 'country': 'Scotland'},
        'Manchester City Reserves': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Östers IF': {'league': 'Division 1 Södra', 'rank': 5, 'country': 'Sweden'},
        'Helsingborgs IF': {'league': 'Allsvenskan', 'rank': 2, 'country': 'Sweden'},
        'Amiens SC': {'league': 'Ligue 2', 'rank': 1, 'country': 'France'},
        'Atlético de Madrid B': {'league': 'Segunda División B', 'rank': 5, 'country': 'Spain'},
        'West Ham United U21': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Atlético Paranaense': {'league': 'Campeonato Brasileiro Série A', 'rank': 9, 'country': 'Brazil'},
        'Club Athletico Paranaense': {'league': 'Campeonato Brasileiro Série A', 'rank': 9, 'country': 'Brazil'},
        'Kilmarnock FC': {'league': 'Scottish Championship', 'rank': 1, 'country': 'Scotland'},
        'Portsmouth FC': {'league': 'EFL League One', 'rank': 1, 'country': 'England'},
        'Swindon Town': {'league': 'EFL League Two', 'rank': 1, 'country': 'England'},
        'Sport Club do Recife': {'league': 'Campeonato Brasileiro Série B', 'rank': 6, 'country': 'Brazil'},
        'Newcastle United U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Everton FC U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Preston North End': {'league': 'EFL Championship', 'rank': 1, 'country': 'England'},
        'Hannover 96': {'league': '2. Bundesliga', 'rank': 5, 'country': 'Germany'},
        'SC Bastia': {'league': 'Unknown', 'rank': None, 'country': 'France'},
        'Club Atlético Lanús': {'league': 'Liga Profesional Argentina', 'rank': 2, 'country': 'Argentina'},
        'Atlanta United FC': {'league': 'Major League Soccer', 'rank': 1, 'country': 'United States'},
        'Coventry City': {'league': 'EFL Championship', 'rank': 1, 'country': 'England'},
        'Sheffield Wednesday': {'league': 'EFL League One', 'rank': 2, 'country': 'England'},
        'AIK Solna': {'league': 'Allsvenskan', 'rank': 3, 'country': 'Sweden'},
        'Coventry City U21': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Legia Warszawa': {'league': 'Ekstraklasa', 'rank': 1, 'country': 'Poland'},
        'FUS Rabat': {'league': 'Botola Pro', 'rank': 2, 'country': 'Morocco'},
        'Torino FC': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'Santos FC B': {'league': 'Unknown', 'rank': None, 'country': 'Brazil'},
        'Santos FC': {'league': 'Campeonato Brasileiro Série A', 'rank': 10, 'country': 'Brazil'},
        'US Palermo': {'league': 'Serie C', 'rank': 1, 'country': 'Italy'},
        'Tranmere Rovers': {'league': 'EFL League Two', 'rank': 2, 'country': 'England'},
        'SK Slavia Prague': {'league': 'Fortuna Liga', 'rank': 1, 'country': 'Czech Republic'},
        'CR Flamengo': {'league': 'Campeonato Brasileiro Série A', 'rank': 1, 'country': 'Brazil'},
        'Málaga CF': {'league': 'Segunda División B', 'rank': 2, 'country': 'Spain'},
        'Angers SCO': {'league': 'Ligue 1', 'rank': 7, 'country': 'France'},
        'GFC Ajaccio': {'league': 'Ligue 2', 'rank': 7, 'country': 'France'},
        'LB Châteauroux': {'league': 'Ligue 2', 'rank': 10, 'country': 'France'},
        'PSV Eindhoven U17': {'league': 'Unknown', 'rank': None, 'country': 'Netherlands'},
        'Sassuolo Primavera': {'league': 'Unknown', 'rank': None, 'country': 'Italy'},
        'US Sassuolo': {'league': 'Serie A', 'rank': 1, 'country': 'Italy'},
        'US Cremonese': {'league': 'Serie B', 'rank': 1, 'country': 'Italy'},
        'PEC Zwolle': {'league': 'Eredivisie', 'rank': 1, 'country': 'Netherlands'},
        'Ascoli Calcio': {'league': 'Serie B', 'rank': 1, 'country': 'Italy'},
        'Unknown': {'league': 'Unknown', 'rank': None, 'country': 'Unknown'},
        'Reading FC': {'league': 'EFL Championship', 'rank': 1, 'country': 'England'},
        'Esbjerg fB U19': {'league': 'Unknown', 'rank': None, 'country': 'Denmark'},
        'Leicester City U21': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Rotherham United': {'league': 'EFL League One', 'rank': 2, 'country': 'England'},
        'Queens Park Rangers': {'league': 'EFL Championship', 'rank': 9, 'country': 'England'},
        'Excelsior Rotterdam': {'league': 'Eerste Divisie', 'rank': 3, 'country': 'Netherlands'},
        'KV Oostende': {'league': 'Belgian First Division A', 'rank': 5, 'country': 'Belgium'},
        'Altinordu FK': {'league': 'TFF 1. Lig', 'rank': 1, 'country': 'Turkey'},
        'SC Freiburg': {'league': 'Bundesliga', 'rank': 1, 'country': 'Germany'},
        'Ross County FC': {'league': 'Scottish Premiership', 'rank': 10, 'country': 'Scotland'},
        'Djurgårdens IF': {'league': 'Allsvenskan', 'rank': 1, 'country': 'Sweden'},
        'TSG 1899 Hoffenheim II': {'league': 'Regionalliga Südwest', 'rank': 2, 'country': 'Germany'},
        'Vitória Guimarães SC': {'league': 'Primeira Liga', 'rank': 7, 'country': 'Portugal'},
        'Luton Town': {'league': 'EFL Championship', 'rank': 3, 'country': 'England'},
        'Milton Keynes Dons': {'league': 'EFL League One', 'rank': 3, 'country': 'England'},
        'FC Liefering': {'league': '2. Liga', 'rank': 3, 'country': 'Austria'},
        'Manchester City U18': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Fleetwood Town': {'league': 'EFL League One', 'rank': 1, 'country': 'England'},
        'Malmö FF': {'league': 'Allsvenskan', 'rank': 1, 'country': 'Sweden'},
        'PAOK Thessaloniki': {'league': 'Super League Greece', 'rank': 3, 'country': 'Greece'},
        'Cagliari Calcio': {'league': 'Serie B', 'rank': 2, 'country': 'Italy'},
        'Doncaster Rovers': {'league': 'EFL League One', 'rank': 2, 'country': 'England'},
        'Ayr United FC': {'league': 'Scottish Championship', 'rank': 1, 'country': 'Scotland'},
        'Burton Albion': {'league': 'EFL League One', 'rank': 1, 'country': 'England'},
        'GD Estoril Praia': {'league': 'Liga Portugal 2', 'rank': 1, 'country': 'Portugal'},
        'FC Nantes': {'league': 'Ligue 1', 'rank': 15, 'country': 'France'},
        'Rayo Vallecano': {'league': 'La Liga', 'rank': 6, 'country': 'Spain'},
        'Elche CF': {'league': 'La Liga', 'rank': 15, 'country': 'Spain'},
        'RSC Anderlecht U19': {'league': 'Unknown', 'rank': None, 'country': 'Belgium'},
        'RSC Anderlecht U21': {'league': 'Unknown', 'rank': None, 'country': 'Belgium'},
        'Hibernian FC': {'league': 'Scottish Premiership', 'rank': 4, 'country': 'Scotland'},
        'Clube de Regatas Vasco da Gama': {'league': 'Campeonato Brasileiro Série B', 'rank': 7, 'country': 'Brazil'},
        'RCD Espanyol Barcelona': {'league': 'La Liga 2', 'rank': 1, 'country': 'Spain'},
        'Cultural Leonesa': {'league': 'Segunda División B', 'rank': 3, 'country': 'Spain'},
        'AJ Auxerre U17': {'league': 'Unknown', 'rank': None, 'country': 'France'},
        'Basaksehir FK': {'league': 'Süper Lig', 'rank': 4, 'country': 'Turkey'},
        'Exeter City': {'league': 'EFL League Two', 'rank': 2, 'country': 'England'},
        'Envigado FC': {'league': 'Categoría Primera A', 'rank': 8, 'country': 'Colombia'},
        'CS Marítimo B': {'league': 'Campeonato de Portugal', 'rank': 3, 'country': 'Portugal'},
        'CS Marítimo': {'league': 'Primeira Liga', 'rank': 12, 'country': 'Portugal'},
        'Southend United U18': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Southend United': {'league': 'National League South', 'rank': 12, 'country': 'England'},
        'Rochdale AFC': {'league': 'EFL League Two', 'rank': 2, 'country': 'England'},
        'Grasshopper Club Zurich': {'league': 'Challenge League', 'rank': 1, 'country': 'Switzerland'},
        'Celta de Vigo': {'league': 'La Liga', 'rank': 10, 'country': 'Spain'},
        'Galatasaray': {'league': 'Süper Lig', 'rank': 1, 'country': 'Turkey'},
        'Sporting CP B': {'league': 'Campeonato de Portugal', 'rank': 2, 'country': 'Portugal'},
        'SC Braga': {'league': 'Primeira Liga', 'rank': 4, 'country': 'Portugal'},
        'SS Lazio': {'league': 'Serie A', 'rank': 6, 'country': 'Italy'},
        'FC Sion': {'league': 'Super League', 'rank': 9, 'country': 'Switzerland'},
        'Hertha BSC': {'league': 'Bundesliga', 'rank': 14, 'country': 'Germany'},
        'CF América': {'league': 'Liga MX', 'rank': 3, 'country': 'Mexico'},
        'Albacete Balompié': {'league': 'Segunda División B', 'rank': 2, 'country': 'Spain'},
        'Without Club': {'league': 'Unknown', 'rank': None, 'country': 'Unknown'},
        'Yeovil Town': {'league': 'National League', 'rank': 6, 'country': 'England'},
        'VfL Bochum': {'league': 'Bundesliga', 'rank': 2, 'country': 'Germany'},
        'Real Valladolid B': {'league': 'Segunda División B', 'rank': 2, 'country': 'Spain'},
        'Lech Poznan': {'league': 'Ekstraklasa', 'rank': 4, 'country': 'Poland'},
        'Gornik Leczna': {'league': 'Ekstraklasa', 'rank': 12, 'country': 'Poland'},
        'Paris FC': {'league': 'Ligue 2', 'rank': 3, 'country': 'France'},
        'Stade Brestois 29': {'league': 'Ligue 1', 'rank': 12, 'country': 'France'},
        'Racing Club': {'league': 'Liga Profesional Argentina', 'rank': 1, 'country': 'Argentina'},
        'Arsenal FC U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Rangers FC': {'league': 'Scottish Premiership', 'rank': 2, 'country': 'Scotland'},
        'FC Nordsjaelland': {'league': 'Superliga', 'rank': 3, 'country': 'Denmark'},
        'Sarpsborg 08 FF': {'league': 'Eliteserien', 'rank': 13, 'country': 'Norway'},
        'Standard Liège': {'league': 'Jupiler Pro League', 'rank': 4, 'country': 'Belgium'},
        'NK Inter Zapresic': {'league': '2. HNL', 'rank': 1, 'country': 'Croatia'},
        'HNK Rijeka': {'league': '1. HNL', 'rank': 2, 'country': 'Croatia'},
        'NK Celje': {'league': 'PrvaLiga', 'rank': 10, 'country': 'Slovenia'},
        'Changchun Yatai': {'league': 'Chinese Super League', 'rank': 3, 'country': 'China'},
        'Ulsan Hyundai': {'league': 'K League 1', 'rank': 1, 'country': 'South Korea'},
        'FC Midtjylland': {'league': 'Superliga', 'rank': 2, 'country': 'Denmark'},
        'Vejle Boldklub': {'league': 'Superliga', 'rank': 10, 'country': 'Denmark'},
        'FC Girondins Bordeaux': {'league': 'Ligue 1', 'rank': 5, 'country': 'France'},
        'Bradford City': {'league': 'EFL League Two', 'rank': 1, 'country': 'England'},
        'RAA La Louviere (- 2009)': {'league': 'Unknown', 'rank': None, 'country': 'Unknown'},
        'Qarabağ FK': {'league': 'Azerbaijan Premier League', 'rank': 1, 'country': 'Azerbaijan'},
        'Oldham Athletic': {'league': 'EFL League Two', 'rank': 4, 'country': 'England'},
        'Shrewsbury Town': {'league': 'EFL League One', 'rank': 2, 'country': 'England'},
        'Independiente Santa Fe': {'league': 'Categoría Primera A', 'rank': 5, 'country': 'Colombia'},
        'Manchester United Reserves': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'Dynamo Kyiv': {'league': 'Ukrainian Premier League', 'rank': 2, 'country': 'Ukraine'},
        'Académica Coimbra': {'league': 'Campeonato de Portugal', 'rank': 1, 'country': 'Portugal'},
        'FC Famalicão': {'league': 'Primeira Liga', 'rank': 11, 'country': 'Portugal'},
        'Sligo Rovers': {'league': 'League of Ireland Premier Division', 'rank': 1, 'country': 'Ireland'},
        'Granada CF': {'league': 'La Liga', 'rank': 9, 'country': 'Spain'},
        'Levante UD': {'league': 'La Liga', 'rank': 14, 'country': 'Spain'},
        'Valenciennes FC': {'league': 'Ligue 2', 'rank': 14, 'country': 'France'},
        'AJ Auxerre': {'league': 'Ligue 2', 'rank': 5, 'country': 'France'},
        'Eastleigh FC': {'league': 'National League', 'rank': 9, 'country': 'England'},
        'Sport Club Corinthians Paulista': {'league': 'Campeonato Brasileiro Série A', 'rank': 6, 'country': 'Brazil'},
        'Norwich City U21': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Peterborough United': {'league': 'EFL Championship', 'rank': 2, 'country': 'England'},
        'Cercle Brugge': {'league': 'Jupiler Pro League', 'rank': 15, 'country': 'Belgium'},
        'FC Toulouse': {'league': 'Ligue 2', 'rank': 10, 'country': 'France'},
        'FC Brüssel': {'league': 'Unknown', 'rank': None, 'country': 'Unknown'},
        'FC Winterthur U21': {'league': 'Unknown', 'rank': None, 'country': 'Switzerland'},
        'FC Luzern': {'league': 'Super League', 'rank': 5, 'country': 'Switzerland'},
        'AC Arles-Avignon': {'league': 'National 2', 'rank': 6, 'country': 'France'},
        'Fenerbahce': {'league': 'Süper Lig', 'rank': 2, 'country': 'Turkey'},
        'Al-Sadd SC': {'league': 'Qatar Stars League', 'rank': 1, 'country': 'Qatar'},
        'FSV Frankfurt': {'league': 'Hessenliga', 'rank': 2, 'country': 'Germany'},
        'Royal Excel Mouscron (-2022)': {'league': 'Belgian First Division B', 'rank': None, 'country': 'Belgium'},
        'KAA Gent': {'league': 'Jupiler Pro League', 'rank': 8, 'country': 'Belgium'},
        'Zorya Lugansk': {'league': 'Ukrainian Premier League', 'rank': 5, 'country': 'Ukraine'},
        '1. FC Köln': {'league': 'Bundesliga', 'rank': 11, 'country': 'Germany'},
        'Falkirk FC': {'league': 'Scottish League One', 'rank': 3, 'country': 'Scotland'},
        'AFC Wimbledon': {'league': 'EFL League One', 'rank': 1, 'country': 'England'},
        'Valencia Mestalla': {'league': 'Segunda División B', 'rank': 3, 'country': 'Spain'},
        'Valencia CF': {'league': 'La Liga', 'rank': 12, 'country': 'Spain'},
        'Recreativo Huelva': {'league': 'Segunda División B', 'rank': 3, 'country': 'Spain'},
        'Crystal Palace U21': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'FC Twente Enschede U21': {'league': 'Unknown', 'rank': None, 'country': 'Netherlands'},
        'FC Dallas': {'league': 'Major League Soccer', 'rank': 1, 'country': 'United States'},
        'Hamilton Academical FC': {'league': 'Scottish Premiership', 'rank': 12, 'country': 'Scotland'},
        'Reading FC U18': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Aldershot Town': {'league': 'National League South', 'rank': 1, 'country': 'England'},
        'NAC Breda': {'league': 'Eredivisie', 'rank': 3, 'country': 'Netherlands'},
        'LDU Quito': {'league': 'Serie A', 'rank': 1, 'country': 'Ecuador'},
        'Granada CF B': {'league': 'Segunda División B', 'rank': 2, 'country': 'Spain'},
        'Independiente del Valle': {'league': 'Serie A', 'rank': 2, 'country': 'Ecuador'},
        'Beerschot V.A.': {'league': 'Jupiler Pro League', 'rank': 11, 'country': 'Belgium'},
        'AA Argentinos Juniors': {'league': 'Liga Profesional Argentina', 'rank': 3, 'country': 'Argentina'},
        'Odra Opole': {'league': 'I Liga', 'rank': 1, 'country': 'Poland'},
        'TSG 1899 Hoffenheim U19': {'league': 'A-Junioren Bundesliga South/Southwest', 'rank': None,
                                    'country': 'Germany'},
        'Karlsruher SC': {'league': '2. Bundesliga', 'rank': 13, 'country': 'Germany'},
        'FC Ingolstadt 04': {'league': '3. Liga', 'rank': 5, 'country': 'Germany'},
        'AIK Solna U19': {'league': 'U19 Allsvenskan', 'rank': None, 'country': 'Sweden'},
        'CA Rosario Central': {'league': 'Liga Profesional Argentina', 'rank': 3, 'country': 'Argentina'},
        'Kawasaki Frontale': {'league': 'J1 League', 'rank': 1, 'country': 'Japan'},
        'Royale Union Saint Gilloise': {'league': 'Proximus League', 'rank': 2, 'country': 'Belgium'},
        'Club Libertad Asunción': {'league': 'División Profesional', 'rank': 2, 'country': 'Paraguay'},
        'Brighton & Hove Albion U23': {'league': 'Premier League 2', 'rank': None, 'country': 'England'},
        'TSV Havelse U19': {'league': 'Unknown', 'rank': None, 'country': 'Germany'},
        'TSV Havelse': {'league': 'Regionalliga Nord', 'rank': 2, 'country': 'Germany'},
        'Eintracht Braunschweig II': {'league': 'Oberliga Niedersachsen', 'rank': None, 'country': 'Germany'},
        'SV Meppen': {'league': '3. Liga', 'rank': 16, 'country': 'Germany'},
        'Lazio U19': {'league': 'Primavera 1', 'rank': None, 'country': 'Italy'},
        'US Salernitana 1919': {'league': 'Serie A', 'rank': 18, 'country': 'Italy'},
        'IK Start': {'league': 'Eliteserien', 'rank': 12, 'country': 'Norway'},
        'Fortuna Düsseldorf': {'league': '2. Bundesliga', 'rank': 9, 'country': 'Germany'},
        'Walsall FC': {'league': 'National League', 'rank': 14, 'country': 'England'},
        'Heart of Midlothian FC': {'league': 'Scottish Championship', 'rank': 2, 'country': 'Scotland'},
        'Vendsyssel FF': {'league': '1st Division', 'rank': 5, 'country': 'Denmark'},
        'Hamburger SV II': {'league': 'Regionalliga Nord', 'rank': 1, 'country': 'Germany'},
        'Bröndby IF': {'league': 'Superliga', 'rank': 3, 'country': 'Denmark'},
        'Syrianska FC': {'league': 'Ettan Norra', 'rank': 3, 'country': 'Sweden'},
        'Östersunds FK': {'league': 'Ettan Norra', 'rank': 2, 'country': 'Sweden'},
        'Stade Lavallois': {'league': 'National', 'rank': 4, 'country': 'France'},
        'FC Nordsjaelland U19': {'league': 'Unknown', 'rank': None, 'country': 'Denmark'},
        'ESTAC Troyes B': {'league': 'National 2', 'rank': None, 'country': 'France'},
        'SC Freiburg II': {'league': 'Regionalliga Südwest', 'rank': 1, 'country': 'Germany'},
        'Northampton Town': {'league': 'EFL League Two', 'rank': 12, 'country': 'England'},
        'Vålerenga Fotball II': {'league': 'Unknown', 'rank': None, 'country': 'Norway'},
        'Vålerenga Fotball': {'league': 'Eliteserien', 'rank': 2, 'country': 'Norway'},
        'SV Eintracht Trier 05 II': {'league': 'Oberliga Rheinland-Pfalz/Saar', 'rank': None, 'country': 'Germany'},
        'SV Eintracht Trier 05': {'league': 'Oberliga Rheinland-Pfalz/Saar', 'rank': 10, 'country': 'Germany'},
        '1.FC Kaiserslautern II': {'league': 'Oberliga Rheinland-Pfalz/Saar', 'rank': None, 'country': 'Germany'},
        '1.FC Kaiserslautern': {'league': '2. Bundesliga', 'rank': 7, 'country': 'Germany'},
        'Betis Deportivo Balompié': {'league': 'Segunda División B', 'rank': 4, 'country': 'Spain'},
        'New York Red Bulls': {'league': 'Major League Soccer', 'rank': 8, 'country': 'United States'},
        'FC Schalke 04 U19': {'league': 'A-Junioren Bundesliga West', 'rank': None, 'country': 'Germany'},
        'Bethlehem Steel FC': {'league': 'USL Championship', 'rank': None, 'country': 'United States'},
        'Philadelphia Union': {'league': 'Major League Soccer', 'rank': 2, 'country': 'United States'},
        'Leeds United U21': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'New York City FC': {'league': 'Major League Soccer', 'rank': 5, 'country': 'United States'},
        'Once Caldas': {'league': 'Categoría Primera A', 'rank': 9, 'country': 'Colombia'},
        'FC Zürich': {'league': 'Super League', 'rank': 3, 'country': 'Switzerland'},
        'FC Dordrecht': {'league': 'Eerste Divisie', 'rank': 14, 'country': 'Netherlands'},
        'Feyenoord U19': {'league': 'Unknown', 'rank': None, 'country': 'Netherlands'},
        'ADO Den Haag': {'league': 'Eredivisie', 'rank': 17, 'country': 'Netherlands'},
        'Stade Rennais FC B': {'league': 'National 2', 'rank': None, 'country': 'France'},
        'VfB Stuttgart U19': {'league': 'A-Junioren Bundesliga South/Southwest', 'rank': None, 'country': 'Germany'},
        'VfB Stuttgart II': {'league': 'Regionalliga Südwest', 'rank': 9, 'country': 'Germany'},
        'Everton FC U18': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Moreirense FC': {'league': 'Primeira Liga', 'rank': 8, 'country': 'Portugal'},
        'FK Partizan Belgrade': {'league': 'Serbian SuperLiga', 'rank': 1, 'country': 'Serbia'},
        'HNK Gorica': {'league': 'Prva HNL', 'rank': 4, 'country': 'Croatia'},
        'Maccabi Petah Tikva': {'league': 'Ligat haAl', 'rank': 5, 'country': 'Israel'},
        'RSC Charleroi': {'league': 'Jupiler Pro League', 'rank': 5, 'country': 'Belgium'},
        'Anzhi Makhachkala ( -2022)': {'league': 'Unknown', 'rank': None, 'country': 'Russia'},
        'Crewe Alexandra': {'league': 'EFL League One', 'rank': 10, 'country': 'England'},
        'Real SC': {'league': 'Campeonato de Portugal', 'rank': 2, 'country': 'Portugal'},
        'AFC Bournemouth U21': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'CA San Lorenzo de Almagro': {'league': 'Liga Profesional Argentina', 'rank': 3, 'country': 'Argentina'},
        'Plymouth Argyle': {'league': 'EFL League One', 'rank': 1, 'country': 'England'},
        'Southampton FC Reserves': {'league': 'Unknown', 'rank': None, 'country': 'England'},
        'Club Nacional': {'league': 'Primera División', 'rank': 2, 'country': 'Uruguay'},
        'Torquay United': {'league': 'National League', 'rank': 2, 'country': 'England'},
        'Oxford United': {'league': 'EFL League One', 'rank': 5, 'country': 'England'},
        'Empoli Primavera': {'league': 'Primavera 1', 'rank': None, 'country': 'Italy'},
        'Empoli FC': {'league': 'Serie A', 'rank': 12, 'country': 'Italy'},
        'Inverness Caledonian Thistle FC': {'league': 'Scottish Championship', 'rank': 1, 'country': 'Scotland'},
        'Viking FK': {'league': 'Eliteserien', 'rank': 3, 'country': 'Norway'}
    }

    # Function to get team details

    if team in team_info:
        return team_info[team]
    else:
        return {'league': 'Unknown', 'rank': None, 'country': 'Unknown'}

    # Test the function with example teams

def get_leage_id(league, country):
    conn = pymysql.connect(host='localhost', user='root',
                           passwd="password", db='economics_of_sports')
    cur = conn.cursor()
    cur.execute("select id from league where name = '" + league +"' and country = '" + country +"'")
    data = list(cur.fetchall())
    conn.close()
    return data
    

def get_teams():
    conn = pymysql.connect(host='localhost', user='root',
                           passwd="password", db='economics_of_sports')
    cur = conn.cursor()
    cur.execute('''select team_name from tm_market_value_raw''')
    data = list(cur.fetchall())
    conn.close()
    return data
    # %%

def team_exist(team_name):
    conn = pymysql.connect(host='localhost', user='root',
                           passwd="password", db='economics_of_sports')
    cur = conn.cursor()
    cur.execute("select * from team where name =  '" + team_name + "'")
    data = list(cur.fetchall())
    conn.close()
    return data
    # %%

def add_team(name, league_id):

    if(len(team_exist(name)) == 0 ):
        try:

            name = name.replace("\'", "''")
            league_id = league_id[0][0]

            conn = pymysql.connect(host='127.0.0.1', unix_socket='/tmp/mysql.sock', user='root',
                                   passwd='password', db='economics_of_sports')
            cur = conn.cursor()

            query = "INSERT INTO team (`name`,`league_id`) VALUES ('%s', '%s');"
            final_query = query % (name, league_id)

            cur.execute(final_query)
            conn.commit()
            cur.close()
            conn.close()
        except Exception as e:
            logging.error(e)

teams = get_teams()

for team in teams:
    team = team[0]
    team_info = get_team_info(team)
    country = team_info['country']
    league = team_info['league']
    league_id = get_leage_id(league, country)
    add_team(team, league_id)



